### ISSUE TITLE
Gør docker image (package) public

### ISSUE THREAD

**Issue by sunekochhansen** [OS2borgerPC/os2borgerpc-admin-site#42]
Der er tilføjet en  byggeprocess (github action) der bygger og releaser det resulterende docker image her på github projektets side via github containerregistry.

Docker imaget har som default fået "private" visibility, hvilket betyder at leverandører der ønsker at drifte produktet ikke har adgang til det, og visibility skal derfor ændres til "public".
Det kræver en "organization administrators" at ændre dette.

Det gøres således:
1. Klik på pakken "os2borgerpc-admin-site"
![Screenshot from 2024-10-24 11-18-25](https://github.com/user-attachments/assets/7a5c65ac-7398-498f-a301-cd67aac3d39d)

2. Klik på "Package settings"
![Screenshot from 2024-10-24 11-18-33](https://github.com/user-attachments/assets/dfd6407b-ffde-430f-a9f1-79defb1d89f2)

3. Klik på "Change visibility"
![Screenshot from 2024-10-24 11-18-46](https://github.com/user-attachments/assets/9a6891e7-6375-441f-99e7-eb09569f2f04)

4. Marker "Public" og indtast "os2borgerpc-admin-site" i feltet og godkend.
![Screenshot from 2024-10-24 11-19-01](https://github.com/user-attachments/assets/7dd85785-af8c-4acb-a1f1-685d099e803f)

**Comment by os2git** [comment]
Tak for udførlige anvisninger. Der var en global indstilling på organisationen som forhindrede at man lavede "public" pakker. Dette er nu ændret og jeg har samtidig ændret indstilling for os2borgerpc-admin-site package.
