### ISSUE TITLE
Versionering af globale/core scripts

### ISSUE THREAD

**Issue by NeutraChikara** [OS2borgerPC/os2borgerpc-admin-site#47]
Vi skal have lavet en måde at ligge versionerede scripts ind i admin-site. Ud over selve scriptet, skal metadata (navn, beskrivelse, inputparametre etc.) også lægges ind.

Der tages udgangspunkt i filerne i https://github.com/OS2borgerPC/os2borgerpc-docs/tree/main/docs/scripts, som parses, og ligges ind i admin site som scripts med tilhørende metadata.
Det er dog ikke alle disse scripts som skal lægges ind, da det kun er de scripts som OS2 ønkser at vedligeholde, som denne opgave indeholder. Disse er dog ikke færdig-definerede endnu, og der tages derfor udgangspunkt i det eksisterende repo, for at kunne komme igang.
Forventningen er derfor, at der skal laves en rettelse til den første løsning beskrevet her, så den bliver tilpasset til det kommende "OS2 core scripts" repo.

**Comment by agnetemoos** [comment]
Vedhæftede undersøgelse danner basis for udvælgelsen af core scripts. Undersøgelsen er lavet at nogle kommuner har afleveret scripthistorik for en typisk borgerpc Det er både store og meget små kommuner. Som udgangspunkt skal flere kommuner bruge et script, før det kan komme på tale at gøre det til core script.
[Scripts - anvendelsesstatistik.xlsx](https://github.com/user-attachments/files/17978303/Scripts.-.anvendelsesstatistik.xlsx)

**Comment by agnetemoos** [comment]
Vi skal have kortlagt hvilke scripts der bruges af admin systemet, og have dem markeret i en særlig kategori. I hvert fald tænd/sluk tidsplan afhænger af scripts. Hvordan får vi dem identificeret? @NeutraChikara @sunekochhansen

**Comment by agnetemoos** [comment]
Det lyder som en god idé med et særskilt repository. Alternativt skal de ligger inde i os2borgerpc-admin-site repo, da de jo faktisk er en bestanddel af systemet. I vælger bare den løsning der giver bedst mening for jer. I må gerne oprette repo, hvis I går den vej.

**Comment by agnetemoos** [comment]
Vi skal have findet ud af hvad vi gør med alle de scripts, der refereres til herfra:
https://github.com/OS2borgerPC/os2borgerpc-image/blob/master/image/scripts/os2borgerpc_setup.sh

Lige nu klones https://github.com/OS2borgerPC/os2borgerpc-scripts. Så det er scripts fra det repo, der ekeskveres når image bygges. https://github.com/OS2borgerPC/os2borgerpc-scripts er ikke en del af core.

Der er pt. to af disse scripts, som Magenta ikke indlæser i mappesystemet i admin. De ligger her: https://github.com/OS2borgerPC/os2borgerpc-scripts/tree/master/images. De minder altså mere om de scripts som admin-systemet afhænger af, som vi aftalte at lægge i særskilt repo.

**Comment by sunekochhansen** [comment]
> Hej @NeutraChikara @sunekochhansen Det lyder som en god idé med et særskilt repository. Alternativt skal de ligger inde i os2borgerpc-admin-site repo, da de jo faktisk er en bestanddel af systemet. I vælger bare den løsning der giver bedst mening for jer. I må gerne oprette repo, hvis I går den vej.

Hej @agnetemoos 
Vi har valgt at lægge dem ind i core-scripts repoet, men tilføjet mulighed for at man kan markere scripts via metadata i markdown-filen. 
Se evt. https://github.com/OS2borgerPC/os2borgerpc-core-scripts/issues/2
