### ISSUE TITLE
Test af installation - os2borgerpcadmin, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by agnetemoos** [OS2borgerPC/os2borgerpc-admin-site#57]
Hej @sunekochhansen og @NeutraChikara 
- Jeg har tjekket master branch ud i os2borgerpc-admin-site og står i roden
- Jeg kører `docker compose up` 

Jeg får: os2borgerpc-admin Warning pull access denied for os2borgerpcadmin, repository does not exist or may require 'docker login': 

dkagms@dev:~/os2borgerpc-admin-site$ docker compose up
[+] Running 17/17
 ✔ db Pulled                                                                                                                                                                                           7.6s 
   ✔ bc0965b23a04 Pull complete                                                                                                                                                                        1.7s 
   ✔ 002e1a8eb6f9 Pull complete                                                                                                                                                                        1.8s 
   ✔ a24f300391ed Pull complete                                                                                                                                                                        1.9s 
   ✔ 627f580b7ad7 Pull complete                                                                                                                                                                        2.2s 
   ✔ cfb3c2203f88 Pull complete                                                                                                                                                                        2.4s 
   ✔ 9e592465b243 Pull complete                                                                                                                                                                        2.5s 
   ✔ 8d4265d09d9c Pull complete                                                                                                                                                                        2.5s 
   ✔ e3a8293e92fd Pull complete                                                                                                                                                                        2.5s 
   ✔ 2cb801c39436 Pull complete                                                                                                                                                                        5.4s 
   ✔ c5fdb20d8658 Pull complete                                                                                                                                                                        5.4s 
   ✔ 67c5fe618f0c Pull complete                                                                                                                                                                        5.4s 
   ✔ c9cdd1fe82e4 Pull complete                                                                                                                                                                        5.5s 
   ✔ 8f152c4aceed Pull complete                                                                                                                                                                        5.6s 
   ✔ 2cd360f3b7db Pull complete                                                                                                                                                                        5.6s 
 ! os2borgerpc-admin Warning pull access denied for os2borgerpcadmin, repository does not exist or may require 'docker login': denied: requested access to the resource i...                       1.6s 
 ✘ cron-service Error       pull access denied for os2borgerpcadmin, repository does not exist or may require 'docker login': denied: requested access to the resource is denie...                     1.6s 
[+] Building 1.6s (19/32)

**Comment by NeutraChikara** [comment]
Hej @agnetemoos, kommer servicen ikke op at køre alligevel? Det ser ud til at den bare klager over at den ikke kan finde/downloade imaget, så den bygger imaget ud fra koden i stedet, og starter.

Det er ikke meningen at den skal downloade imaget nogen steder fra, så jeg retter koden så fejlbeskeden fjernes.

**Comment by agnetemoos** [comment]
@NeutraChikara Servicen kommer ikke op at køre. 
Jeg har vedhæftet det fulde output i en tekstfil. 
[Output from docker compose up.txt](https://github.com/user-attachments/files/18111015/Output.from.docker.compose.up.txt)

**Comment by agnetemoos** [comment]
OK. Det er mit pull request der har lavet rod i det. Men som I også har fundet ud af er afhængighederne i systemerne svære at regne ud. Jeg ville bare luge ud i "Read the docs" men det har måske smadret noget dokumentation i admin-systemet.

Når jeg få adgang til et admin site vil jeg se om der er synlige skader :-)

**Comment by agnetemoos** [comment]
Nu kommer alle containere op at køre. :-)
